export const data = [
    {
        categoria: '1',
        pregunta: 'Cual es la capital de colombia?',
        respuestaTrue: 'Bogota',
        respuestaFalse1: 'Cali',
        respuestaFalse2: 'Medellin',
        respuestaFalse3: 'Armenia',
        
    },
    {
        categoria: '1',
        pregunta: 'Quien es messi?',
        respuestaTrue: 'Footbolista',
        respuestaFalse1: 'Actor',
        respuestaFalse2: 'Cantante',
        respuestaFalse3: 'Presidente de EEUU',
    },
    {
        categoria: '1',
        pregunta: 'Cual es la capital de Antioquia?',
        respuestaTrue: 'Medellin',
        respuestaFalse1: 'Itagui',
        respuestaFalse2: 'Envigado',
        respuestaFalse3: 'Cali',
    },
    {
        categoria: '1',
        pregunta: 'Cual es el oceano mas grande del mundo?',
        respuestaTrue: 'Pacifico',
        respuestaFalse1: 'Atlantico',
        respuestaFalse2: 'Antartico',
        respuestaFalse3: 'Australia',
    },
    {
        categoria: '1',
        pregunta: 'Cual de los siguientes no es un lenguaje de programacion?',
        respuestaTrue: 'html',
        respuestaFalse1: 'Java',
        respuestaFalse2: 'Python',
        respuestaFalse3: 'C#',
    },
    {
        categoria: '1',
        pregunta: 'Quien escribio 100 años de soledad?',
        respuestaTrue: 'Gabriel Garcia',
        respuestaFalse1: 'Mario Mendoza',
        respuestaFalse2: 'Guillermo Arriaga',
        respuestaFalse3: 'Gustavo Petro',
    },
    {
        categoria: '1',
        pregunta: 'Quien fue el creador de GIT?',
        respuestaTrue: 'Linus Torvalds',
        respuestaFalse1: 'Bill Gates',
        respuestaFalse2: 'Steven Jobs',
        respuestaFalse3: 'Juan Amaya',
    },
    {
        categoria: '1',
        pregunta: 'Cual de los siguientes no es un IDE?',
        respuestaTrue: 'Visual Studio Code',
        respuestaFalse1: 'Eclipse',
        respuestaFalse2: 'Intellij IDEA',
        respuestaFalse3: 'NetBeans',
    },
    {
        categoria: '1',
        pregunta: 'El proximo presidente de colombia sera?',
        respuestaTrue: 'Gustavo Petro',
        respuestaFalse1: 'Rodolfo Hernandez',
        respuestaFalse2: 'Daddy Janque',
        respuestaFalse3: 'Don Omar',
    },
    {
        categoria: '1',
        pregunta: 'Cual de lo siguientes no es una distribucion linux?',
        respuestaTrue: 'Windows xp',
        respuestaFalse1: 'Ubuntu',
        respuestaFalse2: 'Debian',
        respuestaFalse3: 'Centos',
    },
    {
        categoria: '1',
        pregunta: 'Quien es el presidente de EEUU?',
        respuestaTrue: 'Joe Bidden',
        respuestaFalse1: 'Alvaro Uribe',
        respuestaFalse2: 'Juan Amaya',
        respuestaFalse3: 'Donal trump',
    },
    {
        categoria: '1',
        pregunta: 'Quien es el presidente de Mexico?',
        respuestaTrue: 'Leopoldo Lopez',
        respuestaFalse1: 'Enrique Peña',
        respuestaFalse2: 'Juan Amaya',
        respuestaFalse3: 'Donal trump',
    },
    {
        categoria: '1',
        pregunta: 'Cual es de estos paises no pertenece a America Sur?',
        respuestaTrue: 'Panama',
        respuestaFalse1: 'Colombia',
        respuestaFalse2: 'Bolivia',
        respuestaFalse3: 'Brasil',
    },
    {
        categoria: '1',
        pregunta: 'Cual es rio mas grande de Colombia?',
        respuestaTrue: 'Amazonas',
        respuestaFalse1: 'Rio Magdalena',
        respuestaFalse2: 'Rio Cauca',
        respuestaFalse3: 'Rio sucio',
    },
    {
        categoria: '1',
        pregunta: 'Quien fue el campeon de la champions?',
        respuestaTrue: 'Real Madrid',
        respuestaFalse1: 'Liverpool',
        respuestaFalse2: 'Manchester city',
        respuestaFalse3: 'America de cali',
    },
    {
        categoria: '1',
        pregunta: 'Quien fue el campeon de la premier leguea?',
        respuestaTrue: 'Manchester City',
        respuestaFalse1: 'Liverpool',
        respuestaFalse2: 'Chelsea',
        respuestaFalse3: 'America de cali',
    },
    {
        categoria: '1',
        pregunta: 'Cual de los siguientes es un gestor de repositorio?',
        respuestaTrue: 'Git',
        respuestaFalse1: 'Java',
        respuestaFalse2: 'Sub',
        respuestaFalse3: 'C#',
    }
];